<template>
    <select>
        <option>Bananas</option>
        <option>Bananas</option>
        <option>Bananas</option>
        <option>Bananas</option>
        <option>Bananas</option>
    </select>
</template>